name: Publish to NPM
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20.x'
      #     registry-url: 'https://registry.npmjs.org'
      # - name: Install dependencies
      #   run: npm install
      # - name: Build
      #   run: npm run build
      # - name: Publish package on NPM 📦
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}